window.ANNIVERSARY = {
  domain: "21092025.com",
  dateISO: "2025-09-21",
  displayDate: "21.09.2025",
  displayDateLong: "21 September 2025",
  names: {
    a: "Sreeram",
    b: "Anagha",
  },
  nativeNames: "",
  eyebrow: "Our anniversary",
  tagline: "The day you said yes",
  between: "తెలుగు · മലയാളം",
  yesLine: "",
  loveLine: "I love you",
  letter: {
    greeting: "Hi Anagha,",
    title: "Happy Anniversary.",
    body: [
      "One full year. Can you believe it?",
      "It passed like a cloud on a windy day. It did mess up my hair a little, but I enjoyed every second of it.",
      "So many things come to my mind when I think about us. Looking back, I see us being happy, sad, angry, confused (and mostly horny), but damn, baby, what a journey this has been. The person I was a year ago would probably be shocked if he could see everything we’ve been through in this one year. But here we are — still together, still loving each other just as much.",
      "It’s been quite a roller coaster for me, honestly. There were moments when I found myself questioning, “Did I make the right choice? Have I just been in a hurry and desperately jumped into something I wasn’t sure about?”",
      "And then all I had to do was close my eyes and imagine you smiling at me.",
      "That one little thought felt like a sip of water after a marathon. The feeling I get in my heart when I finally see you after a long day feels like a cool breeze on a summer night. The assurance I feel when I hear your voice feels like a ray of sunshine breaking through a cloudy day.",
      "And somehow, every time, I find myself blushing when I think about our moments together.",
      "Just the thought of you being by my side makes my heart race. It gets me aroused, with all kinds of thoughts running around in my head. Some naughty, some warm, but in all of them, we’re happy.",
      "What more could I ever ask for?",
      "What more could a person really want?",
      "You are everything I ever wanted in a person. Through thick and thin, we’ve seen so much of each other. The good, the bad, the ugly, the beautiful, the ridiculous — somehow, we’ve managed to experience all of it together.",
      "I love how warm you are. How welcoming you are. Sometimes I genuinely get shocked by how well you handle everything happening around you, and how you somehow find the strength to stand back up and keep pushing forward.",
      "I feel proud when I look at your ambition. I love how much you care about your own people and how deeply you feel for them. I feel jealous sometimes of the people who got to have you in their lives longer than I did. But then I remind myself that I got the chance to know all of you — and somehow, that makes me feel lucky all over again.",
      "I love how grounded you are, how well-mannered you are, and how little you care about what people think of you. I love that carefree side of you. And more than anything, I want to see you grow into an even bigger and better version of yourself — stronger than ever, more confident, and even more giving than you already are.",
      "Thank you for existing in my life.",
      "Thank you for being there for me.",
      "And thank you for being the warm, loving person that you are in a world that can sometimes feel so full of negativity and chaos.",
      "A year ago, we were two people who somehow found each other. Today, I look at you and find it difficult to imagine my life without the person you have become to me.",
      "I don’t know what the next year will bring us. I don’t know how many more roller coasters, arguments, stupid jokes, crazy moments, long nights, quiet moments, adventures, and probably horny thoughts are waiting for us.",
      "But if this first year has taught me anything, it’s that I want to experience them with you.",
      "I love you, Anagha.",
      "I love you more than ever.",
    ],
    signoff: "Your loving boyfriend,",
    signature: "Sreeram",
  },
  story: [
    {
      kicker: "March 2024",
      title: "A little buzz on Bumble",
      text: "Two strangers, a Telugu and a Malayali, from backgrounds that were worlds apart, went searching for studies, fun and a whole new world in the city of Hyderabad — and found something better.",
    },
    {
      kicker: "Those months",
      title: "Easy and exciting",
      text: "Exclusive, energetic and a bright stretch of time. They were looking for just a date and some fun exploring, but found something they could never really let go.",
    },
    {
      kicker: "June 2024",
      title: "Distanced, and a pause",
      text: "She was done with her studies and left for Kerala. He had to stay back. They let go. They thought it was an end. But it hardly was.",
    },
    {
      kicker: "August 2025",
      title: "He went back",
      text: "A whole year passed. They could not forget each other. He went to her, and they spent a day together. A week later, he proposed.",
    },
    {
      kicker: "21 September 2025",
      title: "She said yes",
      text: "Not a wedding. A beginning. The day Anagha said yes, their bond finally had a name, a date, and now a home on the internet: 21.09.2025.",
    },
    {
      kicker: "The year",
      title: "Across states, still us",
      text: "Andhra and Kerala. Telugu and Malayalam. Arts and sciences. The list can go longer, the differences can sound bigger, but they can never pull them apart — same energy, same emotion, the first anniversary of choosing each other anyway.",
    },
  ],
  photos: [
    { src: "photos/1.jpg", caption: "March" },
    { src: "photos/2.jpg", caption: "Those months" },
    { src: "photos/3.jpg", caption: "He went back" },
    { src: "photos/5.jpg", caption: "The yes" },
  ],
  memoryPhotos: [
    { src: "photos/6.jpg", caption: "Bir" },
    { src: "photos/7.jpg", caption: "Our café" },
    { src: "photos/8.jpg", caption: "A birthday" },
    { src: "photos/13.jpg", caption: "Another birthday" },
    { src: "photos/9.jpg", caption: "Rajgundha", wide: true },
  ],
  timePhotos: [
    { src: "photos/10.jpg", caption: "1920s" },
    { src: "photos/12.jpg", caption: "1950s" },
    { src: "photos/11.jpg", caption: "1980s" },
    { src: "photos/14.jpg", caption: "Tokyo, 1980s" },
  ],
  song: {
    src: "",
    title: "",
  },
};
